spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.jyumiicapspsxgucirjd
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8080

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS:28800000}

# ==========================================
# CONFIGURACION DE GMAIL (ENVIO DE OTP)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# REEMPLAZAR: Escribe aqui tu correo personal de Gmail (el que usaste para generar la clave)
spring.mail.username=thiagonahuell123@gmail.com

# Lee la clave de 16 digitos desde tus variables de entorno de Windows
spring.mail.password=${GMAIL_APP_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
